---
# tasks file for while_true_do.sys_java

- name: Manage java Packages
  package:
    name: "{{ wtd_sys_java_package }}"
    state: "{{ wtd_sys_java_package_state }}"
  become: true
  tags:
    - java
    - openjdk
    - package
